name: Herangtunet Blogg
favicon: null
layout_spectrum: 0.84646
typography_spectrum: 0.19339669588953257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad3c9'
    - '#acacac'
    - '#2f59ad'
    - '#1f262c'
    - '#68561d'
  brandStrength: 0.25
  lightness: 0.7292259191162884
  saturation: 0.22444250155240297
  rhythmicContrast: 0.75
purpose: []
