name: Herangtunet Blogg
favicon: null
layout_spectrum: 0.07350969780236483
typography_spectrum: 0.19339669588953257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8340052084531635
  lightness: 0.7292259191162884
  saturation: 0.22444250155240297
  rhythmicContrast: 0.42337428661994636
purpose: []
